trigger:
  branches:
    include:
      - main  

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerRegistry: 'beta'  
  imageName: 'flask-app'

jobs:
- job: Build_and_Deploy
  displayName: 'Build and Deploy Docker Container'

  steps:
    - task: Checkout@1
      displayName: 'Checkout source code'
      inputs:
        repository: self

    - task: Docker@2
      displayName: 'Build Docker image'
      inputs:
        containerRegistry: $(dockerRegistry)  
        repository: $(dockerRegistry)/$(imageName)
        command: 'build'
        Dockerfile: '**/Dockerfile'
        buildContext: '.'
        tags: 'latest'

    - task: Docker@2
      displayName: 'Push Docker image to registry'
      inputs:
        containerRegistry: $(dockerRegistry)
        repository: $(dockerRegistry)/$(imageName)
        command: 'push'
        tags: 'latest'

    - task: AzureWebAppContainer@2
      displayName: 'Deploy to Azure Web App'
      inputs:
        appName: 'my-flask-webapp' 
        containers: |
          [
            {
              "name": "$(dockerRegistry)/$(imageName)",
              "imageTag": "latest"
            }
          ]
        azureSubscription: '12345678-1234-1234-1234-1234567890ab' 
        resourceGroupName: 'myResourceGroup'  
